# default to using the container infrastructure
sudo: false

# use the newer travis-ci build templates
dist: trusty

# selecting c as the language keeps the container to a minimum footprint
language: c

# run make
script: make
